# Generated by Django 3.0.2 on 2020-01-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('state', models.BooleanField(default=True, verbose_name='Видимость на сайте')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'аннонимный блог',
                'db_table': 'annonumus_blog',
            },
        ),
    ]
